name: Deploy to Remote Runner

on:
  push:
    branches: [ main, Sotiredtestingbranch ]  # Adjust branches as needed

jobs:
  deploy:
    runs-on: windows-latest  # Or ubuntu-latest if remote is Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SCP
      run: |
        # Assumes SSH key is set up for remote access
        # Set REMOTE_HOST, REMOTE_PATH, SSH_KEY in secrets
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -r . ${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - name: Restart remote service
      run: |
        ssh ${{ secrets.REMOTE_HOST }} "cd ${{ secrets.REMOTE_PATH }} && ./scripts/install_remote.bat"
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}