name: Deploy to Agent Runner

on:
  push:
    branches: [ main, Sotiredtestingbranch ]  # Adjust branches as needed

jobs:
  deploy:
  runs-on: windows-latest  # Or ubuntu-latest if agent is Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SCP
      run: |
        # Assumes SSH key is set up for agent access
        # Prefer AGENT_HOST, AGENT_PATH, SSH_KEY in secrets; fall back to REMOTE_HOST/REMOTE_PATH
        HOST="${{ secrets.AGENT_HOST || secrets.REMOTE_HOST }}"
        PATH_VAR="${{ secrets.AGENT_PATH || secrets.REMOTE_PATH }}"
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -r . ${HOST}:${PATH_VAR}
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - name: Restart agent service
      run: |
        HOST="${{ secrets.AGENT_HOST || secrets.REMOTE_HOST }}"
        PATH_VAR="${{ secrets.AGENT_PATH || secrets.REMOTE_PATH }}"
        ssh ${HOST} "cd ${PATH_VAR} && ./scripts/install_agent.bat"
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}